### ISSUE TITLE
Building the library

### ISSUE THREAD

**Issue by gurjeet** [tatsuhiro-t/wslay#1]
Hi,

```
Can you please also document how to build the library. I tried automake (version 1.11.1) command and got a bunch of warnings. Do I need to do something different. (I am used to the ./configure && make && make install )
```

$ automake
configure.ac: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal).
configure.ac:34: required file `./config.guess' not found
configure.ac:34:`automake --add-missing' can install `config.guess'
configure.ac:34: required file`./config.sub' not found
configure.ac:34:   `automake --add-missing' can install`config.sub'
configure.ac:45: required file `./install-sh' not found
configure.ac:45:`automake --add-missing' can install `install-sh'
doc/Makefile.am:66: HAVE_SPHINX_BUILD does not appear in AM_CONDITIONAL
lib/Makefile.am:32: Libtool library used but`LIBTOOL' is undefined
lib/Makefile.am:32:   The usual way to define `LIBTOOL' is to add`AC_PROG_LIBTOOL'
lib/Makefile.am:32:   to `configure.ac' and run`aclocal' and `autoconf' again.
lib/Makefile.am:32:   If`AC_PROG_LIBTOOL' is in `configure.ac', make sure
lib/Makefile.am:32:   its definition is in aclocal's search path.
lib/Makefile.am: required file`./depcomp' not found
lib/Makefile.am:   `automake --add-missing' can install`depcomp'
/usr/share/automake-1.11/am/depend2.am: am__fastdepCC does not appear in AM_CONDITIONAL
/usr/share/automake-1.11/am/depend2.am:   The usual way to define `am__fastdepCC' is to add`AC_PROG_CC'
/usr/share/automake-1.11/am/depend2.am:   to `configure.ac' and run`aclocal' and `autoconf' again.
/usr/share/automake-1.11/am/depend2.am: AMDEP does not appear in AM_CONDITIONAL
/usr/share/automake-1.11/am/depend2.am:   The usual way to define`AMDEP' is to add one of the compiler tests
/usr/share/automake-1.11/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_CXX, AC_PROG_OBJC,
/usr/share/automake-1.11/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/share/automake-1.11/am/depend2.am:   to `configure.ac' and run`aclocal' and `autoconf' again.
tests/Makefile.am:24: HAVE_CUNIT does not appear in AM_CONDITIONAL
Makefile.am: required file`./INSTALL' not found
Makefile.am:   `automake --add-missing' can install`INSTALL'
configure.ac:41: required file `config.h.in' not found

**Comment by concatime** [comment]
Could you provide `--disable-docs`? This way, no need for Sphinx.
