### ISSUE TITLE
New Release/Tag?

### ISSUE THREAD

**Issue by DomT4** [tatsuhiro-t/wslay#13]
Is there any chance you could cut a new release or tag for wslay here? The last current release from 2012 no longer compiles on OS X, either with the newest gcc or the newest Clang, which makes it kind of a pain to include or package, and backporting two years of codebase fixes is less than fun :smile_cat:.

The git build however does compile without issue, so a new tag/release would aid in packaging it considerably. Thanks for considering it, whatever the decision!

**Comment by tatsuhiro-t** [comment]
I think it is a good idea.  I'll make a release work this weekend. Thanks.

**Comment by DomT4** [comment]
Thanks! Appreciate that.

**Comment by tatsuhiro-t** [comment]
1.0.0 was released.

**Comment by DomT4** [comment]
Thank you! Builds wonderfully :smiley_cat:
