### ISSUE TITLE
make command raises error

### ISSUE THREAD

**Issue by bamchoh** [tatsuhiro-t/wslay#27]
Could you tell me about my process what is wrong?
When I executed `make`, I face the following error:
```sh
... # some making process
Making all in doc
make[2]: Entering directory `/root/wslay/doc'
make[2]: *** No rule to make target `man/wslay_event_context_server_init.3', needed by `all-am'.  Stop.
make[2]: Leaving directory `/root/wslay/doc'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/wslay'
make: *** [all] Error 2
```

Before I execute `make`, I have executed commands are listed below:
```sh
# autoreconf -i
# automake
# autoconf
# ./configure
```

autoconf version is `autoconf (GNU Autoconf) 2.69`
I'm using docker container on Mac OSX. I'm using ubuntu:latest in the container.

If my English is not clear, you can contact me by twitter with Japanese.
My twitter account is @bamchoh.

**Comment by tatsuhiro-t** [comment]
Probably, you need sphinx-doc package.

**Comment by bamchoh** [comment]
@tatsuhiro-t 
Thank you very much for your advice. You are right. I could make it by installing sphinx-doc.

**Comment by concatime** [comment]
Please provide an option to disable docs.

**Comment by jobs-git** [comment]
yes, why is it forced to build, other distro does not have this sphinx-doc
