### ISSUE TITLE
wslay_event_is_msg_queueable shouldn't check ctx->write_enabled

### ISSUE THREAD

**Issue by rinick** [tatsuhiro-t/wslay#28]
in `wslay_event_send()`, sometimes the network is busy and it receive a error and set `ctx->write_enabled` to 0.

in that case, I just need to wait for another writable event from the socket, then change write_enabled to 1 and call `wslay_event_send()` again. the message that's still in the queue will get sent.

however, before the socket change to writable status, I can't add any new data to the queue with `wslay_event_queue_msg()` because it's checking write_enabled

I'm not sure why it needs that protection, is it a bug? or should I check write_enabled and maintain my own queue

**Comment by tatsuhiro-t** [comment]
I think checking ctx->write_enabled is required since we use it to decide whether we send further data or not.  In wslay_event_send(), setting ctx->write_enabled = 0 means that there is fatal error, and session should be closed.  Could you tell us the execution path where ctx->write_enabled gets 0?

**Comment by rinick** [comment]
wslay_event_send, around line 847
```
        if(r != WSLAY_ERR_WANT_WRITE ||
           (ctx->error != WSLAY_ERR_WOULDBLOCK && ctx->error != 0)) {
          ctx->write_enabled = 0;
          return WSLAY_ERR_CALLBACK_FAILURE;
        }
```

r == -101 and ctx->error == -101

the reason for that is, when sending data to socket with the `write` system  api, it failed with error EAGAIN, which means the socket is busy, need to try again when the socket is ready for write

I don't think this should be treated as a fatal error

**Comment by frenche** [comment]
Hi, I didn't look at the code reference, but the doc mentions you have to call the below when u get EAGAIN:
wslay_event_set_error(ctx, WSLAY_ERR_WOULDBLOCK);

Are you calling it? See example here:
http://wslay.sourceforge.net/tutorial.html

**Comment by rinick** [comment]
@frenche thanks for the help.
after that change it works as expected
