### ISSUE TITLE
Allow PMCE via event-based API (RFC 7692)

### ISSUE THREAD

**Issue by frenche** [tatsuhiro-t/wslay#30]
Hi, I've been trying to implement permessage-deflate atop of wslay's event-based API and encountered a few issue:
- The library currently expects any received message to have 'rsv == 0'.
- UTF-8 validation fails on received messages (according to RFC it should be done upon inflation).
- There is currently no interface to set the 'rsv' value when enqueuing a message.

I've tried to address the above issues as can be found at (draft): https://github.com/frenche/wslay/commit/35fd4eeeea4ee41fd7dbc1c8eb16c1a71b04a8ae
This works against an echo client in Chrome browser but I'm not sure if it is the best to approach.

I was wondering whether to make a PR for the above fixes or perhaps we should consider introducing an alternative API which will allow to register extensions and perhaps even handle them at the library level (and how you'd suggest this API to look like).

Cheers,
Isaac B.

**Comment by tatsuhiro-t** [comment]
I think your current approach is good enough to add least support PMCE.  Integrating PMCE into wslay is easier for application, but it requires us to depend on zlib.  I'm not against this alternative approach though.  But with the current stagnated WebSocket standardizing development, we might better to do minimum effort here.

When we are pursuing the current approach, we have to make sure that we don't break  backward compatibility for older release.  Adding extra field to struct  wslay_event_msg will break it, so we have to introduce new struct, say wslay_event_msg2, and its companion functions.

**Comment by frenche** [comment]
On Mon, May 16, 2016 at 11:10 AM, Tatsuhiro Tsujikawa
<notifications@github.com> wrote:
>
> I think your current approach is good enough to add least support PMCE. Integrating PMCE into wslay is easier for application, but it requires us to depend on zlib. I'm not against this alternative approach though. But with the current stagnated WebSocket standardizing development, we might better to do minimum effort here.


Sounds good, we could compensate late by providing an example, perhaps
including negotiation.

> When we are pursuing the current approach, we have to make sure that we don't break backward compatibility for older release. Adding extra field to struct wslay_event_msg will break it, so we have to introduce new struct, say wslay_event_msg2, and its companion functions.


Ok I'll change and open a PR, however I'd be happy to learn what code
this could break, initially I thought adding struct member only won't
break API, but I notice some code that had 'struct s = {2 ,5]' failed
to compile, so I moved the new member to be the last one and then it
was ok.

**Comment by tatsuhiro-t** [comment]
We'd like to run application without recompiling it.  In general, adding a member to struct may change sizeof(T).  It may cause strange thing if application do some malloc using sizeof(T) or linking an application compiled with the older wslay and the some other library with new wslay.  Most of the case, there would be no problem, but just in case.

**Comment by frenche** [comment]
Thanks for clarifying.
I opened a pull request, please review.

**Comment by frenche** [comment]
Following up discussion on PR #31
