### ISSUE TITLE
Examples do not seem to work

### ISSUE THREAD

**Issue by jmjatlanta** [tatsuhiro-t/wslay#41]
Installed on CentOS 6 and tried also on Ubuntu 16.04LTS, it seems to compile fine. I run the fork-echoserv, and the testclient, and they seem to connect, but nothing happens. Pressing ctrl-C on the server causes the client to exit with the "cant get case count". So that indicates to me that they are connecting to each other.

It seems the testclient is hanging at line 425 (epoll_wait), during the call to get_casecnt.
fork-echoserv is on line 418.

the non-fork version (echoserv) seems to give the same results.

Please let me know if you need any more information, or if I'm missing something.

**Comment by jmjatlanta** [comment]
After closer examination, I see that the testclient doesn't seem to be part of the echoserv, but is something altogether different. Sorry for the disturbance.

**Comment by tatsuhiro-t** [comment]
FTR, testclient is written for Autobahn client test.
