### ISSUE TITLE
New release 1.1.1

### ISSUE THREAD

**Issue by anatoli26** [tatsuhiro-t/wslay#57]
Hi Tatsuhiro,

Could you please tag a new release of wslay? There were a couple of commits since the latest release 1.1.0, but one is important for cyrus-imapd: d72ea2ea9e24032144ab85f840e3aaf8cd5d6e07.

The version 1.1.1 of wslay is marked as a dependency for cyrus-imapd to require this commit, but as it's not yet released, there are difficulties with packaging of this project due to unmet dependency.

Thanks!

A corresponding issue at cyrus-imapd is https://github.com/cyrusimap/cyrus-imapd/issues/3070.

**Comment by tatsuhiro-t** [comment]
Will do.  Give me a few days.

**Comment by tatsuhiro-t** [comment]
v1.1.1 has been released: https://github.com/tatsuhiro-t/wslay/releases/tag/release-1.1.1

**Comment by anatoli26** [comment]
Thanks!
